{
  courses {
    edges {
      node {
        id
        title
        slug
        teaser
        image
        status
        created
        updated
        creator {
          id
        }
      }
    }
  }
}
