query Users {
  users {
    edges {
      node {
        id
        username
        firstName
        lastName
        email
        isActive
      }
    }
  }
},
query UsersByEmail($email: String!) {
  users(email: $email) {
    edges {
      node {
        id
        username
        firstName
        lastName
        email
        isActive
      }
    }
  }
}
